# Generated by Django 5.0.6 on 2024-07-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_role_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordResetToken',
            new_name='passwordreset',
        ),
    ]
