# Generated by Django 5.0.6 on 2024-08-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_staffcourse_module_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcourse',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
