# Generated by Django 5.0.6 on 2024-08-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_staffcourse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcourse',
            name='status',
            field=models.CharField(max_length=2),
        ),
    ]
