# Generated by Django 5.0.6 on 2024-08-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcourse',
            name='type',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
