# Generated by Django 5.0.6 on 2024-09-21 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdept', models.CharField(max_length=150)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_department', to='user.department')),
            ],
        ),
    ]
