# Generated by Django 5.0.6 on 2024-10-13 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.enrollment')),
            ],
        ),
    ]
