# Generated by Django 5.0.6 on 2024-10-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcourse',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
