from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/',views.userlogout, name='logout'),
    path('login/', views.login_page, name='login_page'),
    path('loginfn/', views.loginfn, name='loginfn'),
    path('new_password/<str:token>/',views.reset_password, name='new_password'),
    path('password_reset/',views.password_reset_request,name='password_reset'),
    path('registerfn/', views.registerfn, name='registerfn'),
    path('studentindex/', views.studentindex, name='studentindex'),
    path('baseindex/',views.baseindex,name='baseindex'),
    path('adminindex/',views.adminindex, name='adminindex'), 
    path('active_users/',views.active_users, name='active_users'), 
    path('employee_details/',views.employee_details, name='employee_details'), 
    path('user/<int:user_id>/', views.user_details, name='user_details'),
    path('user_profile/',views.user_profile,name='user_profile'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    path('change_password/',views.change_password,name='change_password'),
    path('profile_view/',views.profile_view,name='profile_view'),
    path('delete_profile_picture/', views.delete_profile_picture, name='delete_profile_picture'),
    path('replace_profile_picture/', views.replace_profile_picture, name='replace_profile_picture'),
    
    
    
    path('add_employee/',views.staff_registration,name='add_employee'),
    path('staff_registration/',views.staff_registration,name='staff_registration'),
    path('validate_current_password/',views.validate_current_password,name='validate_current_password'),
    path('update_password/',views.update_password,name='update_password'),
    path('staff_index/',views.staff_index,name='staff_index'),
    path('update_staff_profile/',views.update_staff_profile,name='update_staff_profile'),
    path('edit_staff_profile/',views.edit_staff_profile,name='edit_staff_profile'),
    path('staff_profile/',views.staff_profile,name='staff_profile'),
    path('employee_details/<int:user_id>/', views.view_employee_profile, name='view_employee_profile'),
    path('deactivate_employee/<int:user_id>/', views.deactivate_employee, name='deactivate_employee'),
    path('deactivated_employee/', views.deactivated_employee, name='deactivated_employee'),
    path('activate_employee/<int:user_id>/', views.activate_employee, name='activate_employee'),
    path('deactivate_user/<int:user_id>/', views.deactivate_user, name='deactivate_user'),
    path('deactivated_user/', views.deactivated_user, name='deactivated_user'),
    path('activate_user/<int:user_id>/', views.activate_user, name='activate_user'),
    path('view_user_profile/<int:user_id>/', views.view_user_profile, name='view_user_profile'),
    
    
    path('view_mycourses/', views.view_mycourses, name='view_mycourses'),
    path('my_courses/',views.my_courses,name='my_courses'),
    path('add_course/', views.add_course, name='add_course'),
    path('add_module/<int:course_id>/', views.add_module, name='add_module'),
    path('add_topic/<int:module_id>/<int:course_id>/', views.add_topic, name='add_topic'),
    
    path('delete_topic/<int:topic_id>/<int:course_id>/', views.delete_topic, name='delete_topic'),
    path('delete_module/<int:module_id>/<int:course_id>/', views.delete_module, name='delete_module'),
    path('edit_course/<int:course_id>', views.edit_course, name='edit_course'),
    path('course_approval/',views.course_approval,name='course_approval'),
    path('request_course//<int:course_id>/',views.request_course,name='request_course'),
    path('request_approval_view/',views.request_approval_view,name='request_approval_view'),
    
    path('approve_course/<int:course_id>/', views.approve_course, name='approve_course'),
    path('reject_course/<int:course_id>/', views.reject_course, name='reject_course'),
    path('view_course_details/<int:course_id>/',views.view_course_details,name='view_course_details'),
    path('course_details/<int:course_id>/',views.course_details,name='course_details'),
    
    path('courses/',views.courses,name='courses'),
    path('course_details_view/<int:course_id>/', views.course_details_view, name='course_details_view'),
    path('employee_course/<int:instructor_id>/', views.employee_course, name='employee_course'),

   
    
    path('add_quiz/<int:course_id>/', views.add_quiz, name='add_quiz'),
    path('edit_question/', views.edit_question, name='edit_question'),
    path('delete_quiz/<int:course_id>/<int:question_id>/', views.delete_quiz, name='delete_quiz'),
    path('each_course/<int:course_id>/', views.each_course, name='each_course'),
    path('course_details_view_staff/<int:course_id>/', views.course_details_view_staff, name='course_details_view_staff'),
    path('upload_excel/<int:course_id>/',views.upload_excel, name='upload_excel'),
    path('edit_topic/<int:course_id>/<int:topic_id>/', views.edit_topic, name='edit_topic'),
     path('enroll_course/<int:course_id>/', views.enroll_course, name='enroll_course'),
     
     path('course_category/',views.course_category,name='course_category'),
     path('add_department/',views.add_department,name='add_department'),
     path('add_subdept/',views.add_subdept,name='add_subdept'),
     path('edit_category/', views.edit_category, name='edit_category'),
     path('remove_category/<int:category_id>/', views.remove_category, name='remove_category'),
     path('active_category/<int:category_id>/', views.active_category, name='active_category'),
     path('update_video_progress/', views.update_video_progress, name='update_video_progress'),
     path('quiz/<int:course_id>/',views.quiz,name='quiz'),
     path('update_score/<int:course_id>/', views.update_score, name='update_score'),
     path('enrolled_courses/', views.enrolled_courses_view, name='enrolled_courses_view'),
     path('course_enrollments/', views.course_enrollment_details, name='course_enrollment_details'),
     path('recommendations/', views.recommendation_view, name='recommendations'),
     path('payment/<int:course_id>/',views.payment,name='payment'),
      path('check-course-name/', views.check_course_name, name='check_course_name'),
       path('check_module_name/<int:course_id>/', views.check_module_name, name='check_module_name'),
    path('check_topic_name/<int:course_id>/', views.check_topic_name, name='check_topic_name'),
    
    path('certificate/<int:course_id>/',views.certificate,name='certificate'),
    path('acheivments/',views.acheivments,name='acheivments'),
    path('save_payment/', views.save_payment, name='save_payment'),
    path('payments/', views.admin_payment_list, name='admin_payment_list'),
    path('enrollment_analysis/', views.enrollment_analysis, name='enrollment_analysis'),
    path('landing/',views.landing,name='landing'),
    # path('get_recommended_courses/', views.get_recommended_courses, name='get_recommended_courses'), 
    path('toggle-course-status/<int:course_id>/', views.toggle_course_status, name='toggle_course_status'),
    path('main_page/',views.main_page,name='main_page'),
    path('approval_history/',views.approval_history,name='approval_history'),
    # path('generate_enrollment_csv/',views.generate_enrollment_csv,name='generate_enrollment_csv'),
    path('course_list/',views.course_list,name='course_list'),
    path('course_details_view_admin/<int:course_id>/',views.course_details_view_admin,name='course_details_view_admin'),
    
    path('delete_course/<int:course_id>/',views.delete_course,name='delete_course'),

]
